---
- name: Display failed run
  hosts: node-1
  tasks:
    - name: Debug result
      ansible.builtin.debug:
        msg: "The playbook failed and we are restoring the config"
      
    - name: Restore nginx.conf
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf